name: Deploy to Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Load Secrets from 1Password
        id: load_secrets
        uses: 1password/load-secrets-action@v3
        with:
          op-cli-version: "v2.24.0"
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          API_ENDPOINT: op://Service Account Vault/VassistantApiEndpoint/credential
          AWS_ACCOUNT_ID: op://Service Account Vault/AWS Account ID/credential
          AWS_ROLE_TO_ASSUME: op://Service Account Vault/IAM Role DeployVassistant/credential
          DOMAIN_NAME: op://Service Account Vault/VassistantDomainName/credential
          HOSTED_ZONE: op://Service Account Vault/VassistantHostedZone/credential
          NEXT_PUBLIC_USER_POOL_ID: op://Service Account Vault/VassistantUserPoolId/credential
          NEXT_PUBLIC_USER_POOL_CLIENT_ID: op://Service Account Vault/VassistantUserPoolClientId/credential

      - name: Add masks for sensitive output
        run: |
          echo "::add-mask::${{ steps.load_secrets.outputs.API_ENDPOINT }}"
          echo "::add-mask::${{ steps.load_secrets.outputs.AWS_ACCOUNT_ID }}"
          echo "::add-mask::${{ steps.load_secrets.outputs.AWS_ROLE_TO_ASSUME }}"
          echo "::add-mask::${{ steps.load_secrets.outputs.DOMAIN_NAME }}"
          echo "::add-mask::${{ steps.load_secrets.outputs.HOSTED_ZONE }}"
          echo "::add-mask::${{ steps.load_secrets.outputs.NEXT_PUBLIC_USER_POOL_ID }}"
          echo "::add-mask::${{ steps.load_secrets.outputs.NEXT_PUBLIC_USER_POOL_CLIENT_ID }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ steps.load_secrets.outputs.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_USER_POOL_ID: ${{ steps.load_secrets.outputs.NEXT_PUBLIC_USER_POOL_ID }}
          NEXT_PUBLIC_USER_POOL_CLIENT_ID: ${{ steps.load_secrets.outputs.NEXT_PUBLIC_USER_POOL_CLIENT_ID }}

      - name: Deploy with SST
        id: deploy
        run: npm run deploy -- --stage prod
        env:
          API_ENDPOINT: ${{ steps.load_secrets.outputs.API_ENDPOINT }}
          DOMAIN_NAME: ${{ steps.load_secrets.outputs.DOMAIN_NAME }}
          HOSTED_ZONE: ${{ steps.load_secrets.outputs.HOSTED_ZONE }}
          NEXT_PUBLIC_USER_POOL_ID: ${{ steps.load_secrets.outputs.NEXT_PUBLIC_USER_POOL_ID }}
          NEXT_PUBLIC_USER_POOL_CLIENT_ID: ${{ steps.load_secrets.outputs.NEXT_PUBLIC_USER_POOL_CLIENT_ID }}
